Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_dsw1.Entity;
using Proyecto_dsw1.Models;

using System.IO;
using System.Drawing;
using System.Drawing.Imaging;
using System.Web.Helpers;
using Proyecto_dsw1.Data;
using System.Collections.Specialized;
using System.Data.Entity;
using Proyecto_dsw1.utils;
using System.Net;

namespace Proyecto_dsw1.Controllers
{
    public class ProductoController : Controller
    {
        proyectoEntities db = new proyectoEntities();
        public JsonResult GetData()
        {
            db.Configuration.LazyLoadingEnabled = false;
            NameValueCollection nvc = HttpUtility.ParseQueryString(Request.Url.Query);
            string sEcho = nvc["sEcho"].ToString();
            string sSearch = nvc["sSearch"].ToString();
            int iDisplayStart = Convert.ToInt32(nvc["iDisplayStart"]);
            int iDisplayLength = Convert.ToInt32(nvc["iDisplayLength"]);

            int iSortCol = Convert.ToInt32(nvc["iSortCol_0"]);
            string sortOrder = nvc["sSortDir_0"].ToString();

            //get total value count
            var Count = db.producto.Count();

            var Students = new List<producto>();

            if (sSearch != "" && sSearch != null)
            {

                Students = db.producto.Where(a => a.nom_prod.ToLower().Contains(sSearch.ToLower())
                                  || a.pre_prod.ToString().Contains(sSearch.ToLower())
                                  || a.des_prod.ToLower().Contains(sSearch.ToLower())
                                  ).Where(x => x.activo == true)
                                  .ToList();

                Count = Students.Count();
                Students = SortFunction(iSortCol, sortOrder, Students).Skip(iDisplayStart).Take(iDisplayLength).ToList();
            }
            else
            {
                Students = db.producto.Where(x => x.activo == true)
                                   .ToList();

                Students = SortFunction(iSortCol, sortOrder, Students).Skip(iDisplayStart).Take(iDisplayLength).ToList();
            }

            var StudentsPaged = new SysDataTablePager<producto>(Students, Count, Count, sEcho);

            return Json(StudentsPaged, JsonRequestBehavior.AllowGet);


        }
        private List<producto> SortFunction(int iSortCol, string sortOrder, List<producto> list)
        {

            //Sorting for String columns
            if (iSortCol == 1 || iSortCol == 0 || iSortCol == 2)
            {
                Func<producto, string> orderingFunction = (c => iSortCol == 0 ? c.nom_prod : iSortCol == 1 ? c.des_prod : iSortCol == 2 ? c.marca : c.nom_prod); // compare the sorting column

                if (sortOrder == "desc")
                {
                    list = list.OrderByDescending(orderingFunction).Where(x => x.activo == true).ToList();
                }
                else
                {
                    list = list.OrderBy(orderingFunction).Where(x => x.activo == true).ToList();

                }
            }


            return list;
        }

        public ActionResult Index(int p=0)
        {

            ViewBag.paginaPadre = "Producto";
            ViewBag.pagina = "Listar";
            ViewBag.accion = "";
            if (verificarSession.sessionEmpleado("Producto") == Constante.NO_LOGUEADO)
                return RedirectToAction("LoginAdmin", "Home");
            else if (verificarSession.sessionEmpleado("Producto") == Constante.LOGUEADO)
                return View();
            else
                return RedirectToAction("LoginAdmin", "Home");
        }
        public ActionResult listaPorGenero(int genero= 0)
        {
            return View(db.producto.Where(x => x.genero.id_genero == genero));
        }
        [HttpPost]
        public ActionResult Buscar(String nombre)
        {
            return View(db.producto.Where(x => x.des_prod == nombre));
        }
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            ViewBag.paginaPadre = "Producto";
            ViewBag.pagina = "Listar";
            ViewBag.accion = "";
            if (file != null && file.ContentLength > 0)
            {
                var filename = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/App_Data/imagenes"), filename);
                file.SaveAs(path);
            }
            return View(db.producto.ToList());
        }
        //public ActionResult Create()
        //{
        //    ViewBag.paginaPadre = "Producto";
        //    ViewBag.pagina = "Nuevo";
        //    ViewBag.accion = "";
        //    ViewBag.categorias = new SelectList(daocategoria.ListaCategoria(), "id_cate", "desc_cate");
        //    ViewBag.generos = new SelectList(daogenero.listaGenero(), "id_genero", "desc_genero");
        //    return View(new Producto());
        //}
        //[HttpPost]
        //public ActionResult Create(Producto pro)
        //{
        //    ViewBag.paginaPadre = "Producto";
        //    ViewBag.pagina = "Nuevo";
        //    ViewBag.accion = "";
        //    try
        //    {

        //        if (ModelState.IsValid)
        //        {
        //            ViewBag.categorias = new SelectList(daocategoria.ListaCategoria(), "id_cate", "desc_cate");
        //            ViewBag.generos = new SelectList(daogenero.listaGenero(), "id_genero", "desc_genero");

        //            HttpPostedFileBase filebase = Request.Files[0];
        //            WebImage image = new WebImage(filebase.InputStream);
        //            pro.imagen = image.GetBytes();

        //            if (filebase != null && filebase.ContentLength > 0)
        //            {
        //                var filename = Path.GetFileName(filebase.FileName);
        //                var path = Path.Combine(Server.MapPath("~/App_Data/imagenes"), filename);
        //                filebase.SaveAs(path);
        //            }

        //            daoproducto.insertaProducto(pro);

        //            return RedirectToAction("index");
        //        }
        //        return RedirectToAction("index");
        //    }
        //    catch (Exception ex)
        //    {
        //        ViewBag.mensaje = ex.ToString();
        //        return View();
        //    }
        ////}
        //public ActionResult Edit(int? id_prod)
        //{
        //    ViewBag.paginaPadre = "Producto";
        //    ViewBag.pagina = "Editar";
        //    ViewBag.accion = "";
        //    ViewBag.categorias = new SelectList(daocategoria.ListaCategoria(), "id_cate", "desc_cate");
        //    ViewBag.generos = new SelectList(daogenero.listaGenero(), "id_genero", "desc_genero");
        //    if (id_prod == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    producto pro = db.producto.Find(id_prod);
        //    if (pro == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    if (verificarSession.sessionEmpleado("Producto") == Constante.NO_LOGUEADO)
        //        return RedirectToAction("LoginAdmin", "Home");
        //    else if (verificarSession.sessionEmpleado("Producto") == Constante.LOGUEADO)
        //        return View(pro);
        //    else
        //        return RedirectToAction("LoginAdmin", "Home");
        //}
        //[HttpPost]
        //public ActionResult Edit([Bind(Include = "id_prod,vc_cod_prod,nom_prod,des_prod,pre_prod,marca,id_genero")]producto pro)
        //{
        //    ViewBag.paginaPadre = "Producto";
        //    ViewBag.pagina = "Nuevo";
        //    ViewBag.accion = "";
        //    try
        //    {
        //        ViewBag.categorias = new SelectList(daocategoria.ListaCategoria(), "id_cate", "desc_cate", pro.id_cate);
        //        ViewBag.generos = new SelectList(daogenero.listaGenero(), "id_genero", "desc_genero", pro.id_cate);

        //        if (ModelState.IsValid)
        //        {
        //            db.Entry(pro).State = EntityState.Modified;
        //            db.SaveChanges();
        //            return RedirectToAction("Index");
        //        }
        //        return RedirectToAction("index");
        //    }
        //    catch (Exception ex)
        //    {
        //        ViewBag.mensaje = ex.ToString();
        //        return View();
        //    }
        //}
        [HttpPost]
        public JsonResult Delete(int id)
        {
            ViewBag.paginaPadre = "Mantenimientos";
            ViewBag.pagina = "empleados";
            producto prod = db.producto.Find(id);
            prod.activo = false;
            db.Entry(prod).State = EntityState.Modified;
            db.SaveChanges();
            string output = "success";

            return Json(output, JsonRequestBehavior.AllowGet);
        }


        public ActionResult getImage(int id_prod = 0)
        {

            producto prod = db.producto.Find(id_prod);
            if (prod.imagen != null)
            {
                byte[] byteimage = prod.imagen;

                MemoryStream ms = new MemoryStream(byteimage);
                Image image = Image.FromStream(ms);

                ms = new MemoryStream();
                image.Save(ms, ImageFormat.Jpeg);
                ms.Position = 0;

                return File(ms, "image/jpg");
            }
            else
            { 
                return null;
            }
        }
    }
}

Controllers/productosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_dsw1.Data;
using System.IO;

namespace Proyecto_dsw1.Controllers
{
    public class productosController : Controller
    {
        private proyectoEntities db = new proyectoEntities();

        // GET: productos
        public ActionResult Index()
        {
            ViewBag.paginaPadre = "Producto";
            ViewBag.pagina = "Listar";
            var producto = db.producto.Include(p => p.categoria).Include(p => p.genero);
            return View(producto.ToList());
        }

        // GET: productos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            producto producto = db.producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // GET: productos/Create
        public ActionResult Create(int? id)
        {
            var imagenes = db.imagen_producto.Where(x => x.in_id_producto == id);
            ViewBag.listadoImagenes = from p in imagenes
                                      select new { p.vc_ruta_imagen};
            ViewBag.paginaPadre = "Producto";
            ViewBag.pagina = "Nuevo";
            ViewBag.id_cate = new SelectList(db.categoria, "id_cate", "desc_cate");
            ViewBag.id_prod = new SelectList(db.genero, "id_genero", "desc_genero");
            return View();
        }

        // POST: productos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_prod,vc_cod_prod,nom_prod,des_prod,pre_prod,marca,imagen,id_genero,id_cate,stock,activo")] producto producto)
        {
            ViewBag.paginaPadre = "Producto";
            ViewBag.pagina = "Nuevo";
            if (ModelState.IsValid)
            {
                db.producto.Add(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_cate = new SelectList(db.categoria, "id_cate", "desc_cate", producto.id_cate);
            ViewBag.id_prod = new SelectList(db.genero, "id_genero", "desc_genero", producto.id_prod);
            return View(producto);
        }

        // GET: productos/Edit/5
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            producto producto = db.producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            ViewBag.paginaPadre = "Producto";
            ViewBag.pagina = "Listar";
            ViewBag.id_cate = new SelectList(db.categoria, "id_cate", "desc_cate", producto.id_cate);
            ViewBag.id_prod = new SelectList(db.genero, "id_genero", "desc_genero", producto.id_prod);
            return View(producto);
        }

        // POST: productos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_prod,vc_cod_prod,nom_prod,des_prod,pre_prod,marca,imagen,id_genero,id_cate,stock,activo")] producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.paginaPadre = "Producto";
            ViewBag.pagina = "Listar";
            ViewBag.id_cate = new SelectList(db.categoria, "id_cate", "desc_cate", producto.id_cate);
            ViewBag.id_prod = new SelectList(db.genero, "id_genero", "desc_genero", producto.id_prod);
            return View(producto);
        }

        // GET: productos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            producto producto = db.producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            producto producto = db.producto.Find(id);
            db.producto.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public static byte[] ConversionImagen(string nombrearchivo)
        {
            //Declaramos fs para poder abrir la imagen.
            FileStream fs = new FileStream(nombrearchivo, FileMode.Open);

            // Declaramos un lector binario para pasar la imagen
            // a bytes
            BinaryReader br = new BinaryReader(fs);
            byte[] imagen = new byte[(int)fs.Length];
            br.Read(imagen, 0, (int)fs.Length);
            br.Close();
            fs.Close();
            return imagen;
        }
        void guardarImagen(HttpPostedFileBase file)
        {

            if (file != null && file.ContentLength > 0)
            {
                var filename = Path.GetFileName(file.FileName);
                var ruta = Path.Combine(Server.MapPath("~/imagenes"), filename);
                file.SaveAs(ruta);
            }
        }
    }
}

Views/productos/Create.cshtml
@model Proyecto_dsw1.Data.producto

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

       
        <div class="form-group">
            @Html.LabelFor(model => model.id_prod, "id_prod", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_prod", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vc_cod_prod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vc_cod_prod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vc_cod_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom_prod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_prod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.des_prod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.des_prod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.des_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pre_prod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pre_prod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pre_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_genero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_genero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_cate, "id_cate", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_cate", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_cate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.activo)
                    @Html.ValidationMessageFor(model => model.activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/productos/Delete.cshtml
@model Proyecto_dsw1.Data.producto

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutLoginAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.vc_cod_prod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_cod_prod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nom_prod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_prod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.des_prod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.des_prod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pre_prod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pre_prod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_genero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.activo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoria.desc_cate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria.desc_cate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genero.desc_genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genero.desc_genero)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/productos/Details.cshtml
@model Proyecto_dsw1.Data.producto

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutLoginAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.vc_cod_prod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_cod_prod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nom_prod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_prod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.des_prod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.des_prod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pre_prod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pre_prod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_genero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.activo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoria.desc_cate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria.desc_cate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genero.desc_genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genero.desc_genero)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_prod }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/productos/Edit.cshtml
@model Proyecto_dsw1.Data.producto

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_prod)

        <div class="form-group">
            @Html.LabelFor(model => model.vc_cod_prod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vc_cod_prod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vc_cod_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom_prod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_prod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.des_prod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.des_prod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.des_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pre_prod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pre_prod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pre_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_genero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_genero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_cate, "id_cate", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_cate", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_cate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="d-flex flex-row">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a class="btn btn-outline-primary" href="@Url.Action("Index","productos")">Cancelar</a>
            </div>
        </div>
    </div>
}