Controllers/EnviosController.cs
using HtmlAgilityPack;
using Proyecto_dsw1.utils;
using RadPdf.Web.UI;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Web_Colegio.utils;

namespace Proyecto_dsw1.Controllers
{
    public class EnviosController : Controller
    {
        // GET: Envios
        public ActionResult Index()
        {
            if (verificarSession.sessionEmpleado("Banner") == Constante.NO_LOGUEADO)
                return RedirectToAction("LoginAdmin", "Home");
            else if (verificarSession.sessionEmpleado("Banner") == Constante.NO_AUTORIZADO)
                return RedirectToAction("LoginAdmin", "Home");
            else {  
                ViewBag.paginaPadre = "Envio";
                ViewBag.pagina = "Correo";

                return View();
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Index(string para, string asunto, string body, HttpPostedFileBase file)
        {
            string url = ConfigurationManager.AppSettings["ipPublica"].ToString();
            ViewBag.paginaPadre = "Envio";
            ViewBag.pagina = "Correo";
            var doc = new HtmlDocument();
            doc.LoadHtml(body);
            foreach (var node in doc.DocumentNode.SelectNodes("//img"))
            {
                var src = node.Attributes[@"src"].Value;
                if (src.StartsWith("/"))
                    node.SetAttributeValue("src", url + src);
            }

            var newHtml = doc.DocumentNode.WriteTo();
            EnvioAsincrono(para, asunto, body).Wait();
            return View();
        }
        public ActionResult Cuerpo()
        {
            ViewBag.paginaPadre = "Envio";
            ViewBag.pagina = "Correo";
            return View();
        }
        public async Task EnvioAsincrono(string correo, string asunto, string body)
        {
            EnvioMail mail = new EnvioMail();
            mail.EnvioCorreo("Roberto", asunto, correo, body);
        }
        public void getImage(byte[] binario)
        {
            byte[] byteimage = binario;

            MemoryStream ms = new MemoryStream(byteimage);
            Image image = Image.FromStream(ms);

            ms = new MemoryStream();
            image.Save(ms, ImageFormat.Jpeg);
            ms.Position = 0;

            // return File(ms, "image/jpg");


        }

        public static byte[] ConversionImagen(string nombrearchivo)
        {
            //Declaramos fs para poder abrir la imagen.
            FileStream fs = new FileStream(nombrearchivo, FileMode.Open);

            // Declaramos un lector binario para pasar la imagen
            // a bytes
            BinaryReader br = new BinaryReader(fs);
            byte[] imagen = new byte[(int)fs.Length];
            br.Read(imagen, 0, (int)fs.Length);
            br.Close();
            fs.Close();
            return imagen;
        }


        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult LoadFile(HttpPostedFileBase file)
        {
            var vReturnImagePath = string.Empty;
            if (file.ContentLength > 0)
            {
                var vFileName = Path.GetFileNameWithoutExtension(file.FileName);
                var vExtension = Path.GetExtension(file.FileName);

                string sImageName = vFileName + DateTime.Now.ToString("YYYYMMDDHHMMSS");

                var vImageSavePath = Server.MapPath("~/imagenes/") + sImageName + vExtension;
                //sImageName = sImageName + vExtension;  
                vReturnImagePath = "/imagenes/" + sImageName + vExtension;
                ViewBag.Msg = vImageSavePath;
                var path = vImageSavePath;

                // Saving Image in Original Mode  
                file.SaveAs(path);
                var vImageLength = new FileInfo(path).Length;
                //here to add Image Path to You Database ,  
                TempData["message"] = string.Format("Image was Added Successfully");
            }
            return Json(Convert.ToString(vReturnImagePath), JsonRequestBehavior.AllowGet);
        }

    }
}

Views/Envios/Cuerpo.cshtml
@{
    ViewBag.Title = "Cuerpo";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    
    .content {
        width:100%;
        display:flex;
        justify-content:center;
    }
    .cuerpo {
        background:white;
        padding:15px;
        max-width:600px !important;
    }
    img {
       max-width: calc(100% - 5px) !important;
    }
</style>
<div class="content">
    <div class="cuerpo">
        <h2>Titulo ejemplo</h2>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. </p>
        <img src="~/imagenes/imagenYYYY05DD1705SS.jpg" />
    </div>
</div>

Views/Envios/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@using System.Web.UI.WebControls;
@using RadPdf.Web.UI;

<style>

    .note-dropdown-menu {
 min-width: 350px !important;
         }
    form{
        max-width: 600px !important;
    }
</style>
<link href="~/Content/css/select2.min.css" rel="stylesheet" />
<script src="~/Scripts/select2.min.js" type="text/javascript"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>

<div class="row">
    <div class="col-12">
        <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3 d-flex justify-content-between">
                    <h6 class="text-white text-capitalize ps-3">Envio Masivo de Correos</h6>
                </div>
            </div>
            <div class="card-body p-3 pb-2">
                <div class="table-responsive p-0">
                    @using (Html.BeginForm("Index", "Envios", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div class="input-group input-group-outline mb-3 ">
                            <label class="control-label col-md-3">Destinatario</label>
                            <div class="col-md-10">
                                <select class="form-control" id="para" name="para" multiple="multiple">
                                    <option value="Emp">Empleados</option>
                                    <option value="Cli">Clientes</option>
                                </select>
                            </div>
                        </div>
                        <div class="input-group input-group-outline mb-3 ">
                            <label class="control-label col-md-2">Asunto </label>
                            <div class="col-md-10">
                                <input class="form-control" id="asunto" name="asunto" type="text" />
                            </div>
                        </div>

                        <label>Cuerpo</label>
                        <textarea type="text" name="body" id="body"></textarea>
                        @*<div name="body" id="body" class="summernote"></div>*@

                        <input type="submit" value="enviar" class="btn btn-primary px-3 my-2" />
                    }
                </div>
            </div>

        </div>

    </div>
</div>

<script>

    jQuery(document).ready(function () {
        $('#para').select2();
            jQuery('#body').summernote({
                height: "500px",
                callbacks:{

                    onImageUpload: function (files) {
                        sendFile(files);
                    }
                }

            });
        });
        function sendFile(file) {
            datos = new FormData();
            datos.append("file", file[0]);

  fetch('@Url.Action("LoadFile", "Envios")', {
      method: 'POST',
      body: datos
  })
.then(response => response.json())
.then(data => {
    var imgNode = document.createElement('img');  
    imgNode.src = data;
    $('#body').summernote('insertNode', imgNode);  
})
.catch(error => {
console.error(error)
})
}

</script>