Controllers/configuracionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_dsw1.Data;

namespace Proyecto_dsw1.Controllers
{
    public class configuracionesController : Controller
    {
        private proyectoEntities db = new proyectoEntities();
        public ActionResult Edit()
        {
            ViewBag.paginaPadre = "Configuraciones";
            ViewBag.pagina = "Editar";
            ViewBag.accion = "";
            configuraciones configuraciones = db.configuraciones.ToList()[0];
            if (configuraciones == null)
            {
                return HttpNotFound();
            }
            return View(configuraciones);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "in_id,vc_nombre,vc_email,vc_celular,vc_telefono,vc_estado,vc_ruta_imagen,vc_ruta_corta,bt_imagen,dt_fec_reg,vc_user_reg,vc_user_mod,dt_fec_mod")] configuraciones configuraciones, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                guardarImagen(file);
                if (file != null)
                {
                    configuraciones.vc_ruta_imagen = Server.MapPath("~/imagenes").ToString() + "/" + file.FileName;
                    configuraciones.vc_ruta_corta = "../imagenes/" + file.FileName;
                    configuraciones.bt_imagen = ConversionImagen(configuraciones.vc_ruta_imagen);
                }
                db.Entry(configuraciones).State = EntityState.Modified;

                db.SaveChanges();
                ViewBag.mensaje = "success";

            }
            return View(configuraciones);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public static byte[] ConversionImagen(string nombrearchivo)
        {
            //Declaramos fs para poder abrir la imagen.
            FileStream fs = new FileStream(nombrearchivo, FileMode.Open);

            // Declaramos un lector binario para pasar la imagen
            // a bytes
            BinaryReader br = new BinaryReader(fs);
            byte[] imagen = new byte[(int)fs.Length];
            br.Read(imagen, 0, (int)fs.Length);
            br.Close();
            fs.Close();
            return imagen;
        }
        void guardarImagen(HttpPostedFileBase file)
        {

            if (file != null && file.ContentLength > 0)
            {
                var filename = Path.GetFileName(file.FileName);
                var ruta = Path.Combine(Server.MapPath("~/imagenes"), filename);
                file.SaveAs(ruta);
            }
        }
        public ActionResult EditarPagina()
        {
            ViewBag.paginaPadre = "Incio";
            ViewBag.pagina = "inicio";
            ViewBag.accion = "";
            configuraciones configuraciones = db.configuraciones.ToList()[0];
            if (configuraciones == null)
            {
                return HttpNotFound();
            }

            return View();
        }


    }
}

Views/configuraciones/Create.cshtml
@model Proyecto_dsw1.Data.configuraciones

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>configuraciones</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.vc_nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vc_nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vc_nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vc_email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vc_email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vc_email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vc_celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vc_celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vc_celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vc_telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vc_telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vc_telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vc_estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vc_estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vc_estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vc_color_empresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vc_color_empresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vc_color_empresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vc_ruta_imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vc_ruta_imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vc_ruta_imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bt_imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bt_imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bt_imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dt_fec_reg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dt_fec_reg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dt_fec_reg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vc_user_reg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vc_user_reg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vc_user_reg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vc_user_mod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vc_user_mod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vc_user_mod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dt_fec_mod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dt_fec_mod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dt_fec_mod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vc_ruta_corta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vc_ruta_corta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vc_ruta_corta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/configuraciones/Delete.cshtml
@model Proyecto_dsw1.Data.configuraciones

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>configuraciones</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.vc_nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_color_empresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_color_empresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_ruta_imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_ruta_imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bt_imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bt_imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dt_fec_reg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dt_fec_reg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_user_reg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_user_reg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_user_mod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_user_mod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dt_fec_mod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dt_fec_mod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_ruta_corta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_ruta_corta)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/configuraciones/Details.cshtml
@model Proyecto_dsw1.Data.configuraciones

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>configuraciones</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.vc_nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_color_empresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_color_empresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_ruta_imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_ruta_imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bt_imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bt_imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dt_fec_reg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dt_fec_reg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_user_reg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_user_reg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_user_mod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_user_mod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dt_fec_mod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dt_fec_mod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vc_ruta_corta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vc_ruta_corta)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.in_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/configuraciones/Edit.cshtml
@model Proyecto_dsw1.Data.configuraciones

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<style>

    input[type="file"]#file {
        width: 0.1px;
        height: 0.1px;
        opacity: 0;
        overflow: hidden;
        position: absolute;
        z-index: -1;
    }

    label[for="file"] {
        display: block;
        width: 250px;
        color: #fff;
        background-color: #106BA0;
        display: inline-block;
        transition: all .5s;
        cursor: pointer;
        padding: 5px 15px !important;
        text-transform: uppercase;
        text-align: center;
    }
</style>


@using (Html.BeginForm("Edit", "configuraciones", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="d-flex flex-column col-3">
            <img src="@Model.vc_ruta_corta" id="imgLogo" width="250px" height="300px" />

            <label class="btn btn-primary" for="file">Subir archivo</label>
            <input id="file" type="file" name="file" class="input-file" accept="image/*" value="" />
            @Html.HiddenFor(model => model.vc_ruta_imagen)
            @Html.HiddenFor(model => model.vc_ruta_corta)
            @Html.HiddenFor(model => model.bt_imagen)
        </div>


        <div class="col-7">
            @Html.HiddenFor(model => model.in_id)

            <div class="form-group">
                <div class="col-md-10">
                    <h2>@Html.EditorFor(model => model.vc_nombre, new { htmlAttributes = new { @class = "form-control" } })</h2>
                    @Html.ValidationMessageFor(model => model.vc_nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    @Html.EditorFor(model => model.vc_email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.vc_email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    @Html.EditorFor(model => model.vc_celular, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.vc_celular, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    @Html.EditorFor(model => model.vc_telefono, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.vc_telefono, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.HiddenFor(model => model.vc_estado)

            <div class="form-group">
                <div class="d-flex flex-row">
                    <input type="submit" value="Guardar" class="btn btn-primary m-1" />
                    <input type="button" value="Cancelar" class="btn btn-outline-primary m-1" onclick="location.href='@Url.Action("Index","configuraciones")'" />
                </div>
            </div>
        </div>
    </div>
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>

<script type="application/javascript">
    $('input[type=file]').change(function(){
        var filename = $(this).val().split('\\').pop();
        var idname = $(this).attr('id');
        $('span.'+idname).next().find('span').html(filename);
    });
    $(document).ready(function(){
        if('@ViewBag.mensaje' == 'success'){
            Swal.fire(
                '',
                'Guardado con éxito',
                'success'
            )
        }
    });
    if (window.history.replaceState) { // verificamos disponibilidad
        window.history.replaceState(null, null, window.location.href);
    }
    document.cookie = 'cookie2=value2; SameSite=None; Secure';
</script>

Views/configuraciones/Index.cshtml
@model IEnumerable<Proyecto_dsw1.Data.configuraciones>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.vc_nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vc_email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vc_celular)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vc_telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vc_estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vc_color_empresa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vc_ruta_imagen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bt_imagen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dt_fec_reg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vc_user_reg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vc_user_mod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dt_fec_mod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vc_ruta_corta)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.vc_nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.vc_email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.vc_celular)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.vc_telefono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.vc_estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.vc_color_empresa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.vc_ruta_imagen)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.bt_imagen)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dt_fec_reg)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.vc_user_reg)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.vc_user_mod)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dt_fec_mod)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.vc_ruta_corta)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.in_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.in_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.in_id })
        </td>
    </tr>
}

</table>